import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#d0bcff",
        "inverse-on-surface": "#2e3038",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004395",
        "primary-fixed": "#d8e2ff",
        "surface-container-highest": "#32353c",
        "surface-tint": "#adc6ff",
        outline: "#8c909f",
        surface: "#10131a",
        "on-tertiary": "#502400",
        "surface-dim": "#10131a",
        "on-secondary-fixed-variant": "#5516be",
        "surface-container-low": "#191b23",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#723600",
        "inverse-surface": "#e1e2ec",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary": "#002e6a",
        "on-surface": "#e1e2ec",
        "on-secondary": "#3c0091",
        "on-primary-container": "#00285d",
        "on-background": "#e1e2ec",
        background: "#10131a",
        "on-tertiary-fixed": "#311400",
        "outline-variant": "#424754",
        "surface-bright": "#363941",
        primary: "#adc6ff",
        "on-secondary-container": "#c4abff",
        "surface-container-high": "#272a31",
        "tertiary-fixed": "#ffdcc6",
        "surface-variant": "#32353c",
        "primary-container": "#4d8eff",
        "secondary-container": "#571bc1",
        "inverse-primary": "#005ac2",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed": "#23005c",
        "surface-container": "#1d2027",
        "tertiary-container": "#df7412",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#e9ddff",
        "surface-container-lowest": "#0b0e15",
        "on-error": "#690005",
        "on-primary-fixed": "#001a42",
        tertiary: "#ffb786",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary-container": "#461f00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "8px",
        "section-gap": "120px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
